server:
  port: 1111

spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql:  true
    properties:
     hibernate:
      format_sql: true
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
    
        - beans
      base-path: /myactuator
     
        
  endpoint: 
    shutdown:
      enabled: true
  #  health:
   #   show-details: always
   #   show-components: always
      
    
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
      
#info: 
 # createdBy: sony
 # modified: 22jun22
  
      
#logging:
  #level:
  #  com: 
  #  zensar: debug
 
 
      
      
  

   
 

